### PR TITLE
refactor(native): specify stdlib to work around conflicting stdlib

### PR DESCRIPTION
**Pull request by lessp**
There are probably other ways to handle this, but when I passed `-open Tablecloth` to `dune`-flags I'd hit "unbound value List.assoc". This solves that.

### CODE REVIEW

**Comment by anmonteiro** [comment]
How would you ever hit this in practice?

I don't think this patch is reasonable, as it breaks compatibility with OCaml 4.06.

**Comment by lessp** [comment]
> How would you ever hit this in practice?

Hmm, not sure I follow, I did hit this in practice? 

```lisp
(flags
  (-open Tablecloth))
```

> I don't think this patch is reasonable, as it breaks compatibility with OCaml 4.06.

Ah, yes, that's true, thanks. Do you have an alternative suggestion?

**Comment by anmonteiro** [comment]
How did you hit this? are you using Tablecloth to work on this PPX?

**Comment by lessp** [comment]
I'm consuming the ppx in a native project. I'm getting an error message within the ppx-definition that `List.assoc` is unbound.

```
module Foo = [%graphql {|
    query Foo {
      bar
    }
  |}];
```

**Comment by anmonteiro** [comment]
ok fair. I got confused by the diff because you changed references to `List` in both emitted code and PPX code...

**Comment by lessp** [comment]
> ok fair. I got confused by the diff because you changed references to `List` in both emitted code and PPX code...

Ah, I blame `s/List/Stdlibl.List/g` 😄

**Comment by anmonteiro** [comment]
A couple alternatives:

- adding [stdlib-shims](https://opam.ocaml.org/packages/stdlib-shims/) to this project (less desirable to me)
- fix this is tablecloth: Base and Core have `Caml` modules that allow you to recover OCaml stdlib functionality by opening that module. In your case you'd be able to do:

```ocaml
open Caml
(* from this point on, `List` refers to Stdlib.List *)

module YourQuery = [%graphql ...]```

**Comment by lessp** [comment]
> A couple alternatives:
> 
> * adding [stdlib-shims](https://opam.ocaml.org/packages/stdlib-shims/) to this project (less desirable to me)
> * fix this is tablecloth: Base and Core have `Caml` modules that allow you to recover OCaml stdlib functionality by opening that module. In your case you'd be able to do:
> 
> ```ocaml
> open Caml
> (* from this point on, `List` refers to Stdlib.List *)
> 
> module YourQuery = [%graphql ...]```
> ```

Thanks, they both seem reasonable to me, with a slight preference for adding the shims since that means the end-user does not have to worry about the implementation-details of the the ppx at all.
What are some of the downsides for adding those, apart from adding another dependency, that you see? 

Perhaps both alternatives would be the best option. 🙂

**Comment by jfrolich** [comment]
I don't see why you'd want to override the standard lib for all dependencies of the project? Wouldn't that cause massive problems for all dependencies if these new `List` modules are not compatible? For runtime code, I can see the issue.

**Comment by lessp** [comment]
> I don't see why you'd want to override the standard lib for all dependencies of the project? Wouldn't that cause massive problems for all dependencies if these new `List` modules are not compatible? For runtime code, I can see the issue.

I've actually never run in to this before, so my guess was that it only applied to ppx's. But that may be completely off!

**Comment by jfrolich** [comment]
> I've actually never run in to this before, so my guess was that it only applied to ppx's. But that may be completely off!

Interesting. There ought to be a way to turn it of for ppxes :). For the runtime code it makes sense! Do you think we need to support 4.06 on native or should we just increase the minimum version?

**Comment by lessp** [comment]
> > I've actually never run in to this before, so my guess was that it only applied to ppx's. But that may be completely off!
> 
> Interesting. There ought to be a way to turn it of for ppxes :). For the runtime code it makes sense! Do you think we need to support 4.06 on native or should we just increase the minimum version?

Yes, feels like this must've come up before! I can do some more investigation on it.

I haven't used anything less than 4.08 for a while, but you could go with the polyfill-approach (suggested by Antonio) as well, as not to break 4.06.

**Comment by lessp** [comment]
From the OCaml Discord:

> IIRC, ppx_deriving tries to hack around this issue by including everything it needs in a Ppx_deriving_runtime module.  So if it needs Stdlib.List.iter it will alias Stdlib.List as Ppx_deriving_runtime.List and call Ppx_deriving_runtime.List.iter in its generated AST
An update to graphql_ppx to do the same by aliasing its modules under a Graphql_ppx_runtime module might help.  Unfortunately there isn't a good/easy fix from a user's perspective

This may be a better approach for the future if people would keep hitting these, what do you think? I guess we'd still include the shims if support for 4.0.6 is desirable!

**Comment by anmonteiro** [comment]
While I like that approach, and would favor it over stdlib-shims, it would introduce the precedent of shipping a required runtime library with this PPX. 

I'm for it if we _need_ to do it eventually just like the records rewrite involves shipping a runtime BuckleScript library. Otherwise it seems undesirable.

**Comment by jfrolich** [comment]
> While I like that approach, and would favor it over stdlib-shims, it would introduce the precedent of shipping a required runtime library with this PPX.
> 
> I'm for it if we _need_ to do it eventually just like the records rewrite involves shipping a runtime BuckleScript library. Otherwise it seems undesirable.

Yes there is some new functionality in 1.0 that requires a runtime library anyway. So I think this is fine.

**Comment by lessp** [comment]
Seeing as this required a bit more dedication unfortunately I won't have time to pursue this as of now! Closing in favour of: https://github.com/reasonml-community/graphql-ppx/issues/181

**Pull request closed without merging**
